# Generated by Django 5.0.1 on 2024-01-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=200, null=True)),
                ('monthly_salary', models.FloatField(max_length=200, null=True)),
                ('approved_limit', models.FloatField(max_length=200, null=True)),
                ('current_debt', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('loan_id', models.CharField(max_length=200)),
                ('loan_amount', models.CharField(max_length=200, null=True)),
                ('tenure', models.IntegerField(max_length=200, null=True)),
                ('interest_rate', models.FloatField(max_length=200, null=True)),
                ('monthly_repayment', models.FloatField(max_length=200, null=True)),
                ('EMIs_paid_on_time', models.IntegerField(max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True, null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
