# Generated by Django 5.0.1 on 2024-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_alter_loan_emis_paid_on_time_alter_loan_tenure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
